name: test

on:
  push:
  pull_request:

jobs:


  test_linux_big:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: run big test
        run: |
          cd tests/
          time ./t.sh


  test_linux_sqlcipher:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: generate code
        run: |
          javac csorma_generator.java  && java csorma_generator ./project/

      - name: compile binary
        run: |
          cd project/gen/
          ls -al
          ENCRYPT_CS=1 make -j 6 asan_all && ENCRYPT_CS=1 make asan_tests

      - name: check binary
        run: |
          cd project/gen/
          ls -al
          ldd csorma_test
          ls -al csorma_test
          ls -hal csorma_test

      - name: debug
        run: |
          cd project/gen/
          echo "==============="
          cat -n Message.h
          echo "==============="
          cat -n Message.c
          echo "==============="

      - name: run test
        run: |
          cd project/gen/
          ./csorma_test

  test_linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: generate code
        run: |
          javac csorma_generator.java  && java csorma_generator ./project/

      - name: compile binary
        run: |
          cd project/gen/
          ls -al
          make -j 6 asan_all && make asan_tests

      - name: check binary
        run: |
          cd project/gen/
          ls -al
          ldd csorma_test
          ls -al csorma_test
          ls -hal csorma_test

      - name: debug
        run: |
          cd project/gen/
          echo "==============="
          cat -n Message.h
          echo "==============="
          cat -n Message.c
          echo "==============="

      - name: run test
        run: |
          cd project/gen/
          ./csorma_test

  test_macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run:  brew install gdb

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: generate code
        run: |
          javac csorma_generator.java  && java csorma_generator ./project/

      - name: compile binary
        run: |
          cd project/gen/
          ls -al
          export CFLAGS="-fsanitize=address -fno-omit-frame-pointer"
          make -j 6 all && make tests

      - name: check binary
        run: |
          cd project/gen/
          ls -al
          otool -L csorma_example || echo "NO ERR"
          ls -al csorma_example
          ls -hal csorma_example
          otool -L csorma_test || echo "NO ERR"
          ls -al csorma_test
          ls -hal csorma_test

      - name: debug
        run: |
          cd project/gen/
          echo "==============="
          cat -n Message.h
          echo "==============="
          cat -n Message.c
          echo "==============="

      - name: run test
        run: |
          cd project/gen/
          ./csorma_test && ./csorma_example
  test_macos14arm:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: generate code
        run: |
          javac csorma_generator.java  && java csorma_generator ./project/

      - name: compile binary
        run: |
          cd project/gen/
          ls -al
          export CFLAGS="-fsanitize=address -fno-omit-frame-pointer"
          make -j 6 all && make tests

      - name: check binary
        run: |
          cd project/gen/
          ls -al
          otool -L csorma_example || echo "NO ERR"
          ls -al csorma_example
          ls -hal csorma_example
          otool -L csorma_test || echo "NO ERR"
          ls -al csorma_test
          ls -hal csorma_test

      - name: debug
        run: |
          cd project/gen/
          echo "==============="
          cat -n Message.h
          echo "==============="
          cat -n Message.c
          echo "==============="

      - name: run test
        run: |
          cd project/gen/
          ./csorma_test && ./csorma_example
  test_wine:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          wine libwine-dev libwine wine64 wine64-tools winetricks \
          gcc-mingw-w64-x86-64

      - name: check mingw
        run: dpkg -L gcc-mingw-w64-x86-64

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: generate code
        run: |
          javac csorma_generator.java  && java csorma_generator ./project/

      - name: compile binary
        run: |
          cd project/gen/
          ls -al
          export CC=x86_64-w64-mingw32-gcc
          make -j 6 all && make tests

      - name: check binary
        run: |
          cd project/gen/
          ls -al
          file csorma_test.exe
          ls -al csorma_test.exe
          ls -hal csorma_test.exe

      - name: debug
        run: |
          cd project/gen/
          echo "==============="
          cat -n Message.h
          echo "==============="
          cat -n Message.c
          echo "==============="

      - name: run test
        run: |
          cd project/gen/
          wine ./csorma_test.exe
